AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::LanguageExtensions
Description: "Version - v3.0.0: Template to setup the API Gateway app with AWS and Sumo Logic resources for AWS Observability Solution."
Parameters:
  Section1aSumoDeployment:
    Type: String
    Default: ""
    Description: "Enter au, ca, ch, de, eu, esc, fed, jp, kr, us1 or us2"
  Section1bSumoAccessID:
    Type: String
    Description: "Sumo Logic Access ID. Used for Sumo Logic API calls."
    AllowedPattern: ".+"
    ConstraintDescription: "Sumo Logic Access ID can not be empty."
  Section1cSumoAccessKey:
    Type: String
    Description: "Sumo Logic Access Key. Used for Sumo Logic API calls."
    AllowedPattern: ".+"
    ConstraintDescription: "Sumo Logic Access Key can not be empty."
    NoEcho: true
  Section1dRemoveSumoResourcesOnDeleteStack:
    AllowedValues:
      - true
      - false
    Default: true
    Description: "To delete collectors, sources and apps when the stack is deleted, set this parameter to True. Default is True.
                  Deletes the resources created by the stack. Deletion of updated resources will be skipped."
    Type: String
  Section2aInstallApp:
    Type: String
    Description: "Yes - Installs the API Gateway App for the Sumo Logic AWS Observability Solution.
                  No - Skips the installation of this app."
    Default: 'Yes'
    AllowedValues:
      - 'Yes'
      - 'No'

  Section3aParentStackLambdaARN:
    Type: String
    Default: "ParentStackLambdaARN"
    Description: Parent Stack Lambda ARN. Do Not Edit the value.
  MPS3BucketName:
    Type: String
    AllowedPattern: ".+"
    Description: Name of the S3 bucket for your copy of the nested templates.
    Default: "sumologic-appdev-aws-sam-apps"
  MPS3BucketRegion:
    Type: String
    Description: "AWS Region where the S3 bucket for your copy of the nested templates is hosted."
    Default: "us-east-1"
  MPS3KeyPrefix:
    Type: String
    Description: "S3 key prefix that is used to simulate a folder for your copy of the nested templates."
    AllowedPattern: ".+"
    Default: "aws-observability-versions/v3.0.0/templates/"

  Section4aToUpdate:
    Type: String
    Default: ""
    Description: "Force stack update when parent configuration changes"


Mappings:
#  Apps:
#    Bedrock:
#      Name: "Amazon Bedrock"
#      AppId: "8f4fd1aa-3b83-4d2e-b2ef-e8baec880afa"
#
#    BedrockAgentCore:
#      Name: "Amazon Bedrock AgentCore"
#      AppId: "f27e26fc-f272-4849-b6de-9170834b11b4"
  Apps:
    AmazonECS:
      Name: "Amazon ECS(Without Container Insights and Traces)"
      AppId: "b3210735-0917-459e-8d1e-722fee4c22fe"

    AmazonElastiCache:
      Name: "Amazon ElastiCache"
      AppId: "82ab79f5-3e85-4974-852f-5cb8f8028230"

    AmazonOverview:
      Name: "Amazon Overview"
      AppId: "32c8b96c-161c-46d4-b81d-235cc0b56b87"

    AmazonRDS:
      Name: "Amazon RDS"
      AppId: "c32ad59b-ee10-4cd1-8369-3639e8457b1f"

    AmazonSNS:
      Name: "Amazon SNS"
      AppId: "9c203dfb-6088-4a76-b12e-cc3a78ce0df5"

    AmazonSQS:
      Name: "Amazon SQS"
      AppId: "8b57f601-c163-4481-8ae7-d6e212516506"

    AWSAPIGateway:
      Name: "AWS API Gateway"
      AppId: "f1dfe2ea-ee27-4a74-972c-560424b9cb5c"

    AWSApplicationLoadBalancer:
      Name: "AWS Application Load Balancer"
      AppId: "27a17946-e475-4d56-8a8f-bc3fbc0400ca"

    AWSClassicLoadBalancer:
      Name: "AWS Classic Load Balancer"
      AppId: "fb7a2e22-006c-40ea-945c-e73b6b369e7c"

    AWSDynamoDB:
      Name: "AWS DynamoDB"
      AppId: "092203f6-9443-47ca-b2b5-6a4c25e8c14c"

    AWSEC2:
      Name: "AWS EC2"
      AppId: "f14714b5-6e86-40e7-aa6c-970e9182c0be"

    AWSLambda:
      Name: "AWS Lambda"
      AppId: "d71cb5f7-bf92-4fac-984f-33fdaea856f7"

    AWSNetworkLoadBalancer:
      Name: "AWS Network Load Balancer"
      AppId: "5a6e7695-94a9-4548-a44a-054d4e793432"

    HostMetricsEC2:
      Name: "Host Metrics (EC2)"
      AppId: "149c19d7-de3a-483b-a1a7-bbd825916548"

Conditions:
  is_install_app: !Equals [!Ref Section2aInstallApp, "Yes"]

Resources:

  CreateSumoLogicAWSExplorerView:
    Type: Custom::SumoLogicAWSExplorer
    Properties:
      ServiceToken: !Ref Section3aParentStackLambdaARN
      RemoveOnDeleteStack: false
      HierarchyName: "AWS Observability"
      HierarchyLevel: { "entityType": "account","nextLevelsWithConditions": [ ],"nextLevel": { "entityType": "region","nextLevelsWithConditions": [ ],"nextLevel": { "entityType": "namespace","nextLevelsWithConditions": [ { "condition": "AWS/ApplicationElb","level": { "entityType": "loadbalancer","nextLevelsWithConditions": [ ] } },{ "condition": "AWS/ApiGateway","level": { "entityType": "apiname","nextLevelsWithConditions": [ ] } },{ "condition": "AWS/DynamoDB","level": { "entityType": "tablename","nextLevelsWithConditions": [ ] } },{ "condition": "AWS/EC2","level": { "entityType": "instanceid","nextLevelsWithConditions": [ ] } },{ "condition": "AWS/RDS","level": { "entityType": "dbidentifier","nextLevelsWithConditions": [ ] } },{ "condition": "AWS/Lambda","level": { "entityType": "functionname","nextLevelsWithConditions": [ ] } },{ "condition": "AWS/ECS","level": { "entityType": "clustername","nextLevelsWithConditions": [ ] } },{ "condition": "AWS/ElastiCache","level": { "entityType": "cacheclusterid","nextLevelsWithConditions": [ ] } },{ "condition": "AWS/NetworkELB","level": { "entityType": "networkloadbalancer","nextLevelsWithConditions": [ ] } },{ "condition": "AWS/ELB","level": { "entityType": "loadbalancername","nextLevelsWithConditions": [ ] } },{ "condition": "AWS/SNS","level": { "entityType": "topicname","nextLevelsWithConditions": [ ] } },{ "condition": "AWS/SQS","level": { "entityType": "queuename","nextLevelsWithConditions": [ ] } } ] } } }
      SumoAccessID: !Ref Section1bSumoAccessID
      SumoAccessKey: !Ref Section1cSumoAccessKey
      SumoDeployment: !Ref Section1aSumoDeployment

  Fn::ForEach::AppsLoop:
    - AppKey
#    - [Bedrock, BedrockAgentCore]
    - [AmazonECS, AmazonElastiCache, AmazonOverview, AmazonRDS, AmazonSNS, AmazonSQS, AWSAPIGateway, AWSApplicationLoadBalancer, AWSClassicLoadBalancer, AWSDynamoDB, AWSEC2, AWSLambda, AWSNetworkLoadBalancer, HostMetricsEC2]

    - SumoApp${AppKey}:
        Type: Custom::AppV2
        Condition: is_install_app
        Properties:
          ServiceToken: !Ref Section3aParentStackLambdaARN
          Region: !Ref AWS::Region
          AppName: !FindInMap [Apps, !Ref AppKey, Name]
          AppId: !FindInMap [Apps, !Ref AppKey, AppId]
          RemoveOnDeleteStack: !Ref Section1dRemoveSumoResourcesOnDeleteStack
          SumoAccessID: !Ref Section1bSumoAccessID
          SumoAccessKey: !Ref Section1cSumoAccessKey
          SumoDeployment: !Ref Section1aSumoDeployment
          Section4aToUpdate: !Ref Section4aToUpdate

