AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: "Version - v2.11.0: Template to setup Auto Enable ALB Access Logging and Lambda Auto Subscribe Log Groups for AWS Observability Solution."

Parameters:
  SumoLogicResourceRemoveOnDeleteStack:
    AllowedValues:
      - true
      - false
    Default: true
    Description: "To delete collectors, sources and apps when the stack is deleted, set this parameter to True. Default is True.
                  Deletes the resources created by the stack. Deletion of updated resources will be skipped."
    Type: String

  ALBAutoEnableS3Logs:
    AllowedValues:
      - 'Yes'
      - 'No'
    Default: 'Yes'
    Description: "Enable ALB S3 Access Logging"
    Type: String
  ALBAutoEnableS3LogsOptions:
    Type: String
    Description: "New - Automatically enables S3 logging for newly created ALB resources to collect logs for ALB resources. This does not affect ALB resources already collecting logs.
                  Existing - Automatically enables S3 logging for existing ALB resources to collect logs for ALB resources.
                  Both - Automatically enables S3 logging for new and existing ALB resources.
                  None - Skips Automatic S3 Logging enable for ALB resources."
    Default: 'Both'
    AllowedValues:
      - 'New'
      - 'Existing'
      - 'Both'
      - 'None'
  ALBS3LogsBucketName:
    Type: String
    Description: "Provide a name of existing S3 bucket name where you would like to store ALB logs. If this is empty, a new bucket will be created in the region."
    Default: ""

  AutoSubscribeLogGroups:
    AllowedValues:
      - 'Yes'
      - 'No'
    Default: 'Yes'
    Description: "Auto Subscribe Lambda and API Gateway Log Groups"
    Type: String
  AutoSubscribeLogGroupsLambdaOptions:
    Type: String
    Description: "New - Automatically subscribes new log groups to destination to send logs to Sumo Logic.
                  Existing - Automatically subscribes existing log groups to destination to send logs to Sumo Logic.
                  Both - Automatically subscribes new and existing log groups.
                  None - Skips Automatic subscription."
    Default: 'Both'
    AllowedValues:
      - 'New'
      - 'Existing'
      - 'Both'
      - 'None'
  AutoSubscribeDestinationARNType:
    Type: String
    Description: "Destination ARN Type (Lambda or Kinesis) for Cloudwatch Log Sender."
    Default: 'Lambda'
    AllowedValues:
      - 'Lambda'
      - 'Kinesis'
  AutoSubscribeDestinationARN:
    Type: String
    Description: "Enter the Destination ARN (Lambda ARN or Delivery Stream ARN) based on the destination ARN type"
    Default: ""
  AutoSubscribeLambdaLogGroupPattern:
    Type: String
    Default: '\/aws\/(lambda|apigateway|rds)'
    Description: "Enter regex for matching logGroups. Regex will check for the name. Visit https://help.sumologic.com/docs/send-data/collect-from-other-data-sources/autosubscribe-arn-destination/#configuringparameters"
  AutoSubscribeLogGroupByTags:
    Type: String
    Default: ""
    Description: "Enter comma separated key value pairs for filtering logGroups using tags. Ex KeyName1=string,KeyName2=string. This is optional leave it blank if tag based filtering is not needed. Visit https://help.sumologic.com/docs/send-data/collect-from-other-data-sources/autosubscribe-arn-destination/#configuringparameters"
  AutoSubscribeRoleArn:
    Type: String
    Default: ""
    Description: "Enter AWS IAM Role arn in case the destination is Kinesis Firehose stream."

  ELBAutoEnableS3Logs:
    AllowedValues:
      - 'Yes'
      - 'No'
    Default: 'Yes'
    Description: "Enable ELB S3 Access Logging"
    Type: String

  ELBAutoEnableS3LogsOptions:
    Type: String
    Description: "New - Automatically enables S3 logging for newly created ELB resources to collect logs for ELB resources. This does not affect ELB resources already collecting logs.
                  Existing - Automatically enables S3 logging for existing ELB resources to collect logs for ELB resources.
                  Both - Automatically enables S3 logging for new and existing ELB resources.
                  None - Skips Automatic S3 Logging enable for ELB resources."
    Default: 'Both'
    AllowedValues:
      - 'New'
      - 'Existing'
      - 'Both'
      - 'None'

  ELBS3LogsBucketName:
    Type: String
    Description: "Provide a name of existing S3 bucket name where you would like to store ELB logs. If this is empty, a new bucket will be created in the region."
    Default: ""
  
  ELBS3LogsBucketPrefix:
    Type: String
    Description : "Path inside bucket for dumping of Access Logs for classic load balancer"
    Default: "" 

Conditions:
  auto_enable_s3_logs: !Equals [ !Ref ALBAutoEnableS3Logs, 'Yes' ]
  auto_enable_s3_logs_elb: !Equals [ !Ref ELBAutoEnableS3Logs, 'Yes' ]
  auto_subscribe_new_log_groups: !Equals [ !Ref AutoSubscribeLogGroups, 'Yes' ]

  # Condition for Auto Subscribe Lambda
  auto_subscribe_exisitng_log_groups: !Or
    - !Equals [ !Ref AutoSubscribeLogGroupsLambdaOptions, 'Existing' ]
    - !Equals [ !Ref AutoSubscribeLogGroupsLambdaOptions, 'Both' ]

Resources:

  AutoEnableS3LogsAlbAWSResources:
    Type: AWS::Serverless::Application
    Condition: auto_enable_s3_logs
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:956882708938:applications/sumologic-s3-logging-auto-enable
        SemanticVersion: 1.0.14
      Parameters:
        BucketName: !Ref ALBS3LogsBucketName
        BucketPrefix: "elasticloadbalancing"
        AutoEnableLogging: "ALB"
        AutoEnableResourceOptions: !Ref ALBAutoEnableS3LogsOptions
        FilterExpression: "'Type': 'application'|'type': 'application'"
        RemoveOnDeleteStack: !Ref SumoLogicResourceRemoveOnDeleteStack
  
  AutoEnableS3LogsElbAWSResources:
    Type: AWS::Serverless::Application
    Condition: auto_enable_s3_logs_elb
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:956882708938:applications/sumologic-s3-logging-auto-enable
        SemanticVersion: 1.0.14
      Parameters:
        BucketName: !Ref ELBS3LogsBucketName
        BucketPrefix: !Ref ELBS3LogsBucketPrefix
        AutoEnableLogging: "ELB"
        AutoEnableResourceOptions: !Ref ELBAutoEnableS3LogsOptions
        FilterExpression: "'apiVersion': '2012-06-01'"
        RemoveOnDeleteStack: !Ref SumoLogicResourceRemoveOnDeleteStack

  AutoSubscribeLambdaLogGroupsAWSResources:
    Type: AWS::Serverless::Application
    Condition: auto_subscribe_new_log_groups
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:956882708938:applications/sumologic-loggroup-connector
        SemanticVersion: 1.0.14
      Parameters:
        DestinationArnType: !Ref AutoSubscribeDestinationARNType
        DestinationArnValue: !Ref AutoSubscribeDestinationARN
        LogGroupPattern: !Ref AutoSubscribeLambdaLogGroupPattern
        LogGroupTags: !Ref AutoSubscribeLogGroupByTags
        UseExistingLogs: !If [auto_subscribe_exisitng_log_groups, "true", "false"]
        RoleArn: !Ref AutoSubscribeRoleArn