AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: "Version - v2.12.0: Template to setup the Sumo Logic AWS Inventory Source and Root Cause Explorer app."

Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: "Sumo Logic Access Configuration (Required)"
        Parameters:
          - Section1aSumoDeployment
          - Section1bSumoAccessID
          - Section1cSumoAccessKey
          - Section1dSumoOrganizationId
          - Section1eRemoveSumoResourcesOnDeleteStack

      - Label:
          default: "App Details - Sumo Logic Collector Configuration"
        Parameters:
          - Section2aInstallApp
          - Section2bSumoLogicAccountID
          - Section2cAccountAlias
          - Section2dAccountAliasMappingS3URL

      - Label:
          default: "AWS Inventory Source Details"
        Parameters:
          - Section3aCreateAwsInventorySource
          - Section3bAwsInventorySourceName
          - Section3cNamespaces
          - Section3dInventorySourceCategory

      - Label:
          default: "AWS XRay Source Details"
        Parameters:
          - Section4aCreateAwsXRaySource
          - Section4bAwsXRaySourceName
          - Section4cXraySourceCategory

      - Label:
          default: "Local Parameters. Do Not Edit the values."
        Parameters:
          - Section5aParentStackLambdaARN
          - Section5bNestedTemplateVersion

      - Label:
          default: "App Installation and sharing"
        Parameters:
          - Section6aAppInstallLocation
          - Section6bShare

    ParameterLabels:
      Section1aSumoDeployment:
        default: "Sumo Logic Deployment Name"
      Section1bSumoAccessID:
        default: "Sumo Logic Access ID"
      Section1cSumoAccessKey:
        default: "Sumo Logic Access Key"
      Section1dSumoOrganizationId:
        default: "Sumo Logic Organization Id"
      Section1eRemoveSumoResourcesOnDeleteStack:
        default: "Delete Sumo Logic Resources when stack is deleted"

      Section2aInstallApp:
        default: "Create AWS Root Cause Explorer App"
      Section2bSumoLogicAccountID:
        default: "Sumo Logic Account ID"
      Section2cAccountAlias:
        default: "Alias for AWS Account Identification. Please leave this blank if you are using CloudFormation StackSets to deploy the solution in multiple AWS accounts."
      Section2dAccountAliasMappingS3URL:
        default: "S3 URL of a CSV file that maps AWS Account IDs to an Account Alias"

      Section3aCreateAwsInventorySource:
        default: "Create Sumo Logic AWS Inventory Source"
      Section3bAwsInventorySourceName:
        default: "Sumo Logic AWS Inventory Source Name"
      Section3cNamespaces:
        default: "Limit Inventory collection to following namespaces"
      Section3dInventorySourceCategory:
        default: "Sumo Logic AWS Inventory Source Category"

      Section4aCreateAwsXRaySource:
        default: "Create Sumo Logic AWS XRay Source"
      Section4bAwsXRaySourceName:
        default: "Sumo Logic AWS XRay Source Name"
      Section4cXraySourceCategory:
        default: "Sumo Logic AWS Xray Source Category"

      Section5aParentStackLambdaARN:
        default: "If Any, Lambda ARN from parent Stack"
      Section5bNestedTemplateVersion:
        default: "Nested Templates Version"

      Section6aAppInstallLocation:
        default: "App Installation location"
      Section6bShare:
        default: "Share"

Parameters:
  Section1aSumoDeployment:
    Type: String
    Default: ""
    Description: "Enter au, ca, de, eu, fed, in, jp, kr, us1 or us2"
  Section1bSumoAccessID:
    Type: String
    Description: "Sumo Logic Access ID. Used for Sumo Logic API calls."
    AllowedPattern: ".+"
    ConstraintDescription: "Sumo Logic Access ID can not be empty."
  Section1cSumoAccessKey:
    Type: String
    Description: "Sumo Logic Access Key. Used for Sumo Logic API calls."
    AllowedPattern: ".+"
    ConstraintDescription: "Sumo Logic Access Key can not be empty."
    NoEcho: true
  Section1dSumoOrganizationId:
    Description: "Appears on the Account Overview page that displays information about your Sumo Logic organization. Used for IAM Role in Sumo Logic AWS Sources."
    Type: String
    AllowedPattern: ".+"
    ConstraintDescription: "Sumo Logic Organization Id can not be empty."
  Section1eRemoveSumoResourcesOnDeleteStack:
    AllowedValues:
      - true
      - false
    Default: true
    Description: "To delete collectors, sources and apps when the stack is deleted, set this parameter to True. Default is True.
                  Deletes the resources created by the stack. Deletion of updated resources will be skipped."
    Type: String

  Section2aInstallApp:
    Type: String
    Description: "Yes - Installs the Root Cause Explorer App for the Sumo Logic AWS Observability Solution.
                  No - Skips the installation of this app."
    Default: 'Yes'
    AllowedValues:
      - 'Yes'
      - 'No'
  Section2bSumoLogicAccountID:
    Type: String
    Description: "Provide the Sumo Logic Account ID for trust relationship."
    Default: ""

  Section2cAccountAlias:
    Type: String
    Description: "Provide an Alias for AWS account for identification in Sumo Logic Explorer View, metrics and logs. Please do not include special characters."
    AllowedPattern: "[a-z0-9]*"
    ConstraintDescription: "Alias must only contain lowercase letters, number and length less than or equal to 30 characters."
    MaxLength: 30

  Section2dAccountAliasMappingS3URL:
    Type: String
    Description: "Required only if you are using CloudFormation StackSets to deploy the solution in multiple AWS accounts."
    Default: ""

  Section3aCreateAwsInventorySource:
    Type: String
    Description: "Choose Yes to create Sumo Logic Aws Inventory Source. Choose No to skip Source Creation."
    Default: 'Yes'
    AllowedValues:
      - 'Yes'
      - 'No'
  Section3bAwsInventorySourceName:
    Type: String
    Description: "Change the Aws Inventory Source name to be created else default name will be used."
    Default: ""
  Section3cNamespaces:
    Default: ""
    Description: "Provide Comma delimited list of the namespaces to collect. For Eg.- AWS/ApplicationELB, AWS/ApiGateway, AWS/DynamoDB, AWS/Lambda, AWS/RDS"
    Type: CommaDelimitedList
  Section3dInventorySourceCategory:
    Type: String
    Description: "Change the Aws Inventory Source Category to be created else default name will be used."
    Default: ""

  Section4aCreateAwsXRaySource:
    Type: String
    Description: "Choose Yes to create Sumo Logic Aws XRay Source. Choose No to skip Source Creation."
    Default: 'Yes'
    AllowedValues:
      - 'Yes'
      - 'No'
  Section4bAwsXRaySourceName:
    Type: String
    Description: "Change the Aws XRay Source name to be created else default name will be used."
    Default: ""
  Section4cXraySourceCategory:
    Type: String
    Description: "Change the Aws Xray Source Category to be created else default name will be used."
    Default: ""

  Section5aParentStackLambdaARN:
    Type: String
    Default: "ParentStackLambdaARN"
    Description: Parent Stack Lambda ARN. Do Not Edit the value.
  Section5bNestedTemplateVersion:
    Type: String
    Description: "Provide the version for the nested templates. Default is the latest version."
    AllowedPattern: ".+"

  Section6aAppInstallLocation:
    Type: String
    Description: "Personal Folder - Installs App in user's Personal folder.
                  Admin Recommended Folder - Installs App in admin Recommended Folder"
    Default: 'Personal Folder'
    AllowedValues:
      - 'Personal Folder'
      - 'Admin Recommended Folder'
  Section6bShare:
    Type: String
    Description: "True - Installed App will be visible to all members of the organisation.
                  False - Installed App will be visible to you only."
    Default: 'True'
    AllowedValues:
      - 'True'
      - 'False'

Conditions:

  install_app: !Equals [!Ref Section2aInstallApp, 'Yes']

  install_inventory_source: !Equals [!Ref Section3aCreateAwsInventorySource, 'Yes']

  install_xray_source: !Equals [!Ref Section4aCreateAwsXRaySource, 'Yes']

  install_collector: !Or
    - !Condition install_inventory_source
    - !Condition install_xray_source


Mappings:
  # Bucket names where the Lambda Zip and Nested Templates are kept. Buckets are present in region, with region as suffix.
  # Some buckets names have 's' in the region suffix. It is kept intentional as bucket names were not available.
  # Buckets names which are intentional -
  # 1. appdevzipfiles-eu-north-1s
  # 2. appdevzipfiles-ap-east-1s
  # 3. appdevzipfiles-af-south-1s
  # 4. appdevzipfiles-me-south-1s
  RegionMap:
    us-east-1:
      bucketname: appdevzipfiles-us-east-1
    us-east-2:
      bucketname: appdevzipfiles-us-east-2
    us-west-1:
      bucketname: appdevzipfiles-us-west-1
    us-west-2:
      bucketname: appdevzipfiles-us-west-2
    ap-south-1:
      bucketname: appdevzipfiles-ap-south-1
    ap-northeast-2:
      bucketname: appdevzipfiles-ap-northeast-2
    ap-southeast-1:
      bucketname: appdevzipfiles-ap-southeast-1
    ap-southeast-2:
      bucketname: appdevzipfiles-ap-southeast-2
    ap-northeast-1:
      bucketname: appdevzipfiles-ap-northeast-1
    ca-central-1:
      bucketname: appdevzipfiles-ca-central-1
    eu-central-1:
      bucketname: appdevzipfiles-eu-central-1
    eu-west-1:
      bucketname: appdevzipfiles-eu-west-1
    eu-west-2:
      bucketname: appdevzipfiles-eu-west-2
    eu-west-3:
      bucketname: appdevzipfiles-eu-west-3
    eu-north-1:
      bucketname: appdevzipfiles-eu-north-1s
    sa-east-1:
      bucketname: appdevzipfiles-sa-east-1
    ap-east-1:
      bucketname: appdevzipfiles-ap-east-1s
    af-south-1:
      bucketname: appdevzipfiles-af-south-1s
    eu-south-1:
      bucketname: appdevzipfiles-eu-south-1
    me-south-1:
      bucketname: appdevzipfiles-me-south-1s
    me-central-1:
      bucketname: appdevzipfiles-me-central-1
    eu-central-2:
        bucketname: appdevzipfiles-eu-central-2ss
    ap-northeast-3:
        bucketname: appdevzipfiles-ap-northeast-3s
    ap-southeast-3:
        bucketname: appdevzipfiles-ap-southeast-3

Resources:

  LambdaRole:
    Type: AWS::IAM::Role
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W11
            reason: "Operations are performed across resources."
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: AwsObservabilityLambdaExecutePolicies
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'

  LambdaHelper:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: main.handler
      Runtime: python3.13
      CodeUri:
        Bucket: !FindInMap [ RegionMap, !Ref 'AWS::Region', bucketname ]
        Key: "sumologic-aws-observability/apps/SumoLogicAWSObservabilityHelper/SumoLogicAWSObservabilityHelperv2.0.21.zip"
      MemorySize: 128
      Timeout: 900
      Role:
        Fn::GetAtt:
          - LambdaRole
          - Arn

  AccountAliasValue:
    Type: Custom::AccountAlias
    Properties:
      ServiceToken: !GetAtt LambdaHelper.Arn
      Region: !Ref "AWS::Region"
      AccountID: !Ref "AWS::AccountId"
      AccountAlias: !Ref Section2cAccountAlias
      AccountAliasMappingS3Url: !Ref Section2dAccountAliasMappingS3URL
      SumoAccessID: !Ref Section1bSumoAccessID
      SumoAccessKey: !Ref Section1cSumoAccessKey
      SumoDeployment: !Ref Section1aSumoDeployment

  CloudTrailDevOps:
    Type: Custom::App
    Condition: install_app
    Properties:
      ServiceToken: !Ref Section5aParentStackLambdaARN
      Region: !Ref "AWS::Region"
      AppName: "Global Intelligence for CloudTrail DevOps"
      AppId: "c7e195de-f169-460a-8e8b-7bb23af0ee5e"
      AppSources:
        CloudTrailLogSrc: "account=* eventSource"
      FolderName: !Sub "AWS Observability ${Section5bNestedTemplateVersion} "
      RetainOldAppOnUpdate: true
      RemoveOnDeleteStack: !Ref Section1eRemoveSumoResourcesOnDeleteStack
      SumoAccessID: !Ref Section1bSumoAccessID
      SumoAccessKey: !Ref Section1cSumoAccessKey
      SumoDeployment: !Ref Section1aSumoDeployment
      location: !Ref Section6aAppInstallLocation
      share: !Ref Section6bShare
      orgid: !Ref Section1dSumoOrganizationId

  SumoLogicHostedCollector:
    Type: Custom::Collector
    Condition: install_collector
    Properties:
      ServiceToken: !Ref Section5aParentStackLambdaARN
      Region: !Ref "AWS::Region"
      CollectorType: Hosted
      RemoveOnDeleteStack: !Ref Section1eRemoveSumoResourcesOnDeleteStack
      CollectorName: !Sub
        - "aws-observability-${Alias}-${Number}"
        - Alias: !GetAtt AccountAliasValue.ACCOUNT_ALIAS
          Number: !Ref AWS::AccountId
      SumoAccessID: !Ref Section1bSumoAccessID
      SumoAccessKey: !Ref Section1cSumoAccessKey
      SumoDeployment: !Ref Section1aSumoDeployment

  RootCauseRole:
    Type: AWS::IAM::Role
    Condition: install_collector
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W11
            reason: "Operations are performed across resources."
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${Section2bSumoLogicAccountID}:root"
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: !Sub "${Section1aSumoDeployment}:${Section1dSumoOrganizationId}"
      Path: "/"
      Policies:
        - PolicyName: SumoInventoryPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - apigateway:GET
                  - autoscaling:Describe*
                  - cloudfront:GetDistributionConfig
                  - cloudfront:ListDistributions
                  - cloudtrail:DescribeTrails
                  - cloudtrail:GetTrailStatus
                  - cloudwatch:Describe*
                  - cloudwatch:Get*
                  - cloudwatch:List*
                  - codedeploy:List*
                  - codedeploy:BatchGet*
                  - dynamodb:Describe*
                  - dynamodb:List*
                  - ec2:Describe*
                  - ecs:Describe*
                  - ecs:List*
                  - elasticache:Describe*
                  - elasticache:List*
                  - elasticfilesystem:Describe*
                  - elasticloadbalancing:Describe*
                  - elasticmapreduce:Describe*
                  - elasticmapreduce:List*
                  - es:Describe*
                  - es:List*
                  - health:Describe*
                  - kinesis:Describe*
                  - kinesis:List*
                  - lambda:List*
                  - mq:Describe*
                  - mq:List*
                  - rds:Describe*
                  - rds:List*
                  - redshift:Describe*
                  - route53:List*
                  - sqs:ListQueues
                  - ses:GetSendStatistics
                  - ses:GetSendQuota
                  - sns:List*
                  - tag:GetResources
                  - tag:GetTagKeys
                  - tag:GetTagValues
                  - xray:BatchGetTraces
                  - xray:Get*
                  - pi:DescribeDimensionKeys
                  - pi:GetResourceMetrics
                Effect: Allow
                Resource: "*"

  InventorySource:
    Type: Custom::AWSSource
    Condition: install_inventory_source
    Properties:
      ServiceToken: !Ref Section5aParentStackLambdaARN
      Region: !Ref "AWS::Region"
      RemoveOnDeleteStack: !Ref Section1eRemoveSumoResourcesOnDeleteStack
      SourceType: AwsInventory
      Namespaces: !Ref Section3cNamespaces
      SourceName: !Ref Section3bAwsInventorySourceName
      SourceCategory: !Ref Section3dInventorySourceCategory
      CollectorId: !GetAtt SumoLogicHostedCollector.COLLECTOR_ID
      SumoAccessID: !Ref Section1bSumoAccessID
      SumoAccessKey: !Ref Section1cSumoAccessKey
      SumoDeployment: !Ref Section1aSumoDeployment
      RoleArn: !GetAtt RootCauseRole.Arn

  XraySource:
    Type: Custom::AWSSource
    Condition: install_xray_source
    Properties:
      ServiceToken: !Ref Section5aParentStackLambdaARN
      Region: !Ref "AWS::Region"
      RemoveOnDeleteStack: !Ref Section1eRemoveSumoResourcesOnDeleteStack
      SourceType: AwsXRay
      SourceName: !Ref Section4bAwsXRaySourceName
      SourceCategory: !Ref Section4cXraySourceCategory
      CollectorId: !GetAtt SumoLogicHostedCollector.COLLECTOR_ID
      SumoAccessID: !Ref Section1bSumoAccessID
      SumoAccessKey: !Ref Section1cSumoAccessKey
      SumoDeployment: !Ref Section1aSumoDeployment
      RoleArn: !GetAtt RootCauseRole.Arn