AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: "Version - v2.7.0: Template to setup the Lambda app with AWS and Sumo Logic resources for AWS Observability Solution."

Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: "Sumo Logic Access Configuration (Required)"
        Parameters:
          - Section1aSumoDeployment
          - Section1bSumoAccessID
          - Section1cSumoAccessKey
          - Section1dRemoveSumoResourcesOnDeleteStack
          - Section1eOrgId

      - Label:
          default: "Sumo Logic AWS Resources Tagging Configuration (Required)"
        Parameters:
          - Section2aAccountAlias
          - Section2bAccountAliasMappingS3URL

      - Label:
          default: "App Details - Sumo Logic App Configuration"
        Parameters:
          - Section3aInstallApp

      - Label:
          default: "App Details - CloudWatch Metrics Source Configuration"
        Parameters:
          - Section4aCloudWatchExistingSourceAPIUrl

      - Label:
          default: "App Details - CloudTrail Log Source Configuration"
        Parameters:
          - Section5aCloudTrailLogsAPIUrl
          - Section5bCloudTrailLogsSourceName

      - Label:
          default: "App Details - CloudWatch Log Source Configuration"
        Parameters:
          - Section6aCloudWatchLogsAPIUrl
          - Section6bCloudWatchLogsSourceName

      - Label:
          default: "Local Parameters. Do Not Edit the values."
        Parameters:
          - Section7aParentStackLambdaARN
          - Section7bTemplatesBucketName
          - Section7cNestedTemplateVersion

      - Label:
          default: "App Installation and sharing"
        Parameters:
          - Section8aAppInstallLocation
          - Section8bShare

    ParameterLabels:
      Section1aSumoDeployment:
        default: "Sumo Logic Deployment Name"
      Section1bSumoAccessID:
        default: "Sumo Logic Access ID"
      Section1cSumoAccessKey:
        default: "Sumo Logic Access Key"
      Section1dRemoveSumoResourcesOnDeleteStack:
        default: "Delete Sumo Logic Resources when stack is deleted"
      Section1eOrgId:
        default: "Sumo Logic Organization Id"

      Section2aAccountAlias:
        default: "Alias for AWS Account Identification. Please leave this blank if you are using CloudFormation StackSets to deploy the solution in multiple AWS accounts."

      Section2bAccountAliasMappingS3URL:
        default: "S3 URL of a CSV file that maps AWS Account IDs to an Account Alias"

      Section3aInstallApp:
        default: "Install Sumo Logic App"

      Section4aCloudWatchExistingSourceAPIUrl:
        default: "Existing Sumo Logic CloudWatch Metrics Source API URL"

      Section5bCloudTrailLogsSourceName:
        default: "Sumo Logic CloudTrail Logs Source Name"
      Section5aCloudTrailLogsAPIUrl:
        default: "Existing Sumo Logic ALB Logs Source API URL"

      Section6bCloudWatchLogsSourceName:
        default: "Sumo Logic CloudWatch Logs Source Name"
      Section6aCloudWatchLogsAPIUrl:
        default: "Existing Sumo Logic ALB Logs Source API URL"

      Section7aParentStackLambdaARN:
        default: "If Any, Lambda ARN from parent Stack"
      Section7bTemplatesBucketName:
        default: "Nested Templates Bucket Name"
      Section7cNestedTemplateVersion:
        default: "Nested Templates Version"

      Section8aAppInstallLocation:
        default: "App Installation location"
      Section8bShare:
        default: "Share"

Parameters:
  Section1aSumoDeployment:
    Type: String
    Default: ""
    Description: "Enter au, ca, de, eu, jp, us2, in, fed or us1."
  Section1bSumoAccessID:
    Type: String
    Description: "Sumo Logic Access ID. Used for Sumo Logic API calls."
    AllowedPattern: ".+"
    ConstraintDescription: "Sumo Logic Access ID can not be empty."
  Section1cSumoAccessKey:
    Type: String
    Description: "Sumo Logic Access Key. Used for Sumo Logic API calls."
    AllowedPattern: ".+"
    ConstraintDescription: "Sumo Logic Access Key can not be empty."
    NoEcho: true
  Section1dRemoveSumoResourcesOnDeleteStack:
    AllowedValues:
      - true
      - false
    Default: true
    Description: "To delete collectors, sources and apps when the stack is deleted, set this parameter to True. Default is True.
                  Deletes the resources created by the stack. Deletion of updated resources will be skipped."
    Type: String
  Section1eOrgId:
    Description: "Appears on the Account Overview page that displays information about your Sumo Logic organization. Used for IAM Role in Sumo Logic AWS Sources. Visit https://help.sumologic.com/01Start-Here/05Customize-Your-Sumo-Logic-Experience/Preferences-Page"
    Type: String
    AllowedPattern: ".+"
    ConstraintDescription: "Sumo Logic Organization Id can not be empty."

  Section2aAccountAlias:
    Type: String
    Description: "Provide an Alias for AWS account for identification in Sumo Logic Explorer View, metrics and logs. Please do not include special characters."
    AllowedPattern: "[a-z0-9]*"
    ConstraintDescription: "Alias must only contain lowercase letters, number and length less than or equal to 30 characters."
    MaxLength: 30

  Section2bAccountAliasMappingS3URL:
    Type: String
    Description: "Required only if you are using CloudFormation StackSets to deploy the solution in multiple AWS accounts."
    Default: ""

  Section3aInstallApp:
    Type: String
    Description: "Yes - Installs the Lambda App for the Sumo Logic AWS Observability Solution.
                  No - Skips the installation of this app."
    Default: 'Yes'
    AllowedValues:
      - 'Yes'
      - 'No'

  Section4aCloudWatchExistingSourceAPIUrl:
    Type: String
    Description: "Required when already collecting Lambda Metrics. Provide the existing Sumo Logic Lambda Metrics Source API URL. Account Field will be added to the Source. For Source API URL, visit https://help.sumologic.com/03Send-Data/Sources/03Use-JSON-to-Configure-Sources/Local-Configuration-File-Management/View-or-Download-Source-JSON-Configuration"
    Default: ""

  Section5bCloudTrailLogsSourceName:
    Type: String
    Description: Change the CloudTrail Source name to be created else default name will be used.
    Default: ""
  Section5aCloudTrailLogsAPIUrl:
    Type: String
    Description: "Required when already collecting CloudTrail logs. Provide the existing Sumo Logic CloudTrail Source API URL. Account Field will be added to the Source. For Source API URL, visit https://help.sumologic.com/03Send-Data/Sources/03Use-JSON-to-Configure-Sources/Local-Configuration-File-Management/View-or-Download-Source-JSON-Configuration"
    Default: ""

  Section6bCloudWatchLogsSourceName:
    Type: String
    Description: Change the CloudWatch Log Source name to be created else default name will be used.
    Default: ""
  Section6aCloudWatchLogsAPIUrl:
    Type: String
    Description: "Required when already collecting CloudWatch logs. Provide the existing Sumo Logic CloudWatch Source API URL. Account Field will be added to the Source. For Source API URL, visit https://help.sumologic.com/03Send-Data/Sources/03Use-JSON-to-Configure-Sources/Local-Configuration-File-Management/View-or-Download-Source-JSON-Configuration"
    Default: ""

  Section7aParentStackLambdaARN:
    Type: String
    Default: "ParentStackLambdaARN"
    Description: Parent Stack Lambda ARN. Do Not Edit the value.
  Section7bTemplatesBucketName:
    Type: String
    AllowedPattern: ".+"
    Description: Bucket Name for all the nested templates.
  Section7cNestedTemplateVersion:
    Type: String
    Description: "Provide the version for the nested templates. Default is the latest version."
    AllowedPattern: ".+"

  Section8aAppInstallLocation:
    Type: String
    Description: "Personal Folder - Installs App in user's Personal folder.
                  Admin Recommended Folder - Installs App in admin Recommended Folder"
    Default: 'Personal Folder'
    AllowedValues:
      - 'Personal Folder'
      - 'Admin Recommended Folder'
  Section8bShare:
    Type: String
    Description: "True - Installed App will be visible to all members of the organisation.
                  False - Installed App will be visible to you only."
    Default: 'True'
    AllowedValues:
      - 'True'
      - 'False'

Conditions:
  install_app: !Equals [!Ref Section3aInstallApp, 'Yes']

  update_cloudtrail_logs_source: !Not [!Equals [!Ref Section5aCloudTrailLogsAPIUrl, '']]

  update_cloudwatch_logs_source: !Not [!Equals [!Ref Section6aCloudWatchLogsAPIUrl, '']]

  update_metrics_source: !Not [!Equals [!Ref Section4aCloudWatchExistingSourceAPIUrl, '']]

  create_fer: !Or
    - !Condition update_cloudtrail_logs_source
    - !Not [!Equals [!Ref Section5bCloudTrailLogsSourceName, '']]

  create_cloudwatch_fer: !Or
    - !Condition update_cloudwatch_logs_source
    - !Not [!Equals [!Ref Section6bCloudWatchLogsSourceName, '']]

Resources:

  AccountAliasValue:
    Type: Custom::AccountAlias
    Properties:
      ServiceToken: !Ref Section7aParentStackLambdaARN
      Region: !Ref "AWS::Region"
      AccountID: !Ref "AWS::AccountId"
      AccountAlias: !Ref Section2aAccountAlias
      AccountAliasMappingS3Url: !Ref Section2bAccountAliasMappingS3URL
      SumoAccessID: !Ref Section1bSumoAccessID
      SumoAccessKey: !Ref Section1cSumoAccessKey
      SumoDeployment: !Ref Section1aSumoDeployment

  sumoApp:
    Type: Custom::App
    Condition: install_app
    Properties:
      ServiceToken: !Ref Section7aParentStackLambdaARN
      Region: !Ref "AWS::Region"
      AppName: "AWS Observability Lambda App"
      RemoveOnDeleteStack: !Ref Section1dRemoveSumoResourcesOnDeleteStack
      FolderName: !Sub "AWS Observability ${Section7cNestedTemplateVersion} "
      RetainOldAppOnUpdate: true
      SumoAccessID: !Ref Section1bSumoAccessID
      SumoAccessKey: !Ref Section1cSumoAccessKey
      SumoDeployment: !Ref Section1aSumoDeployment
      AppJsonS3Url: !Sub "https://${Section7bTemplatesBucketName}.s3.amazonaws.com/aws-observability-versions/${Section7cNestedTemplateVersion}/appjson/Lambda-App.json"
      location: !Ref Section8aAppInstallLocation
      share: !Ref Section8bShare
      orgid: !Ref Section1eOrgId

  SumoCloudTrailLogsUpdateSource:
    Type: Custom::SumoLogicUpdateFields
    Condition: update_cloudtrail_logs_source
    Properties:
      ServiceToken: !Ref Section7aParentStackLambdaARN
      Region: !Ref "AWS::Region"
      RemoveOnDeleteStack: !Ref Section1dRemoveSumoResourcesOnDeleteStack
      SourceApiUrl: !Ref Section5aCloudTrailLogsAPIUrl
      SumoAccessID: !Ref Section1bSumoAccessID
      SumoAccessKey: !Ref Section1cSumoAccessKey
      SumoDeployment: !Ref Section1aSumoDeployment
      Fields:
        account: !GetAtt AccountAliasValue.ACCOUNT_ALIAS

  SumoMetricsUpdateSource:
    Type: Custom::SumoLogicUpdateFields
    Condition: update_metrics_source
    Properties:
      ServiceToken: !Ref Section7aParentStackLambdaARN
      Region: !Ref "AWS::Region"
      RemoveOnDeleteStack: !Ref Section1dRemoveSumoResourcesOnDeleteStack
      SourceApiUrl: !Ref Section4aCloudWatchExistingSourceAPIUrl
      SumoAccessID: !Ref Section1bSumoAccessID
      SumoAccessKey: !Ref Section1cSumoAccessKey
      SumoDeployment: !Ref Section1aSumoDeployment
      Fields:
        account: !GetAtt AccountAliasValue.ACCOUNT_ALIAS
        accountid: !Ref "AWS::AccountId"

  SumoHTTPUpdateSource:
    Type: Custom::SumoLogicUpdateFields
    Condition: update_cloudwatch_logs_source
    Properties:
      ServiceToken: !Ref Section7aParentStackLambdaARN
      Region: !Ref "AWS::Region"
      RemoveOnDeleteStack: !Ref Section1dRemoveSumoResourcesOnDeleteStack
      SourceApiUrl: !Ref Section6aCloudWatchLogsAPIUrl
      SumoAccessID: !Ref Section1bSumoAccessID
      SumoAccessKey: !Ref Section1cSumoAccessKey
      SumoDeployment: !Ref Section1aSumoDeployment
      Fields:
        account: !GetAtt AccountAliasValue.ACCOUNT_ALIAS
        namespace: "aws/lambda"
        region: !Ref "AWS::Region"
        accountid: !Ref "AWS::AccountId"

  LambdaFieldExtractionRule:
    Type: Custom::SumoLogicFieldExtractionRule
    Condition: create_fer
    DependsOn: AddFunctionNameField
    Properties:
      ServiceToken: !Ref Section7aParentStackLambdaARN
      RemoveOnDeleteStack: false
      FieldExtractionRuleName: "AwsObservabilityFieldExtractionRule"
      FieldExtractionRuleScope: !Join
        - ""
        - - "(_source="
          - !If [update_cloudtrail_logs_source, !Sub "\"${SumoCloudTrailLogsUpdateSource.source_name}\"", !Ref Section5bCloudTrailLogsSourceName]
          - " (\"lambda.amazonaws.com\"))"
      FieldExtractionRuleParseExpression: '| json "eventSource", "awsRegion", "requestParameters", "recipientAccountId" as eventSource, region, requestParameters, accountid nodrop
                                           | where eventSource = "lambda.amazonaws.com"
                                           | json field=requestParameters "functionName", "resource" as functionname, resource nodrop
                                           | parse regex field=functionname "\w+:\w+:\S+:[\w-]+:\S+:\S+:(?<functionname>[\S]+)$" nodrop
                                           | parse field=resource "arn:aws:lambda:*:function:*" as f1, functionname2 nodrop
                                           | if (isEmpty(functionname), functionname2, functionname) as functionname
                                           | "aws/lambda" as namespace
                                           | tolowercase(functionname) as functionname
                                           | fields region, namespace, functionname, accountid'
      FieldExtractionRuleParseEnabled: true
      SumoAccessID: !Ref Section1bSumoAccessID
      SumoAccessKey: !Ref Section1cSumoAccessKey
      SumoDeployment: !Ref Section1aSumoDeployment

  LambdaCloudWatchLogsFieldExtractionRule:
    Type: Custom::SumoLogicFieldExtractionRule
    Condition: create_cloudwatch_fer
    DependsOn: AddFunctionNameField
    Properties:
      ServiceToken: !Ref Section7aParentStackLambdaARN
      RemoveOnDeleteStack: false
      FieldExtractionRuleName: "AwsObservabilityLambdaCloudWatchLogsFER"
      FieldExtractionRuleScope: !Join
        - ""
        - - "(_source="
          - !If [update_cloudwatch_logs_source, !Sub "\"${SumoHTTPUpdateSource.source_name}\"", !Ref Section6bCloudWatchLogsSourceName]
          - " _sourceHost=/aws/lambda/*)"
      FieldExtractionRuleParseExpression: '| parse field=_sourceHost "/aws/lambda/*" as functionname
                                           | tolowercase(functionname) as functionname
                                           | "aws/lambda" as namespace
                                           | fields functionname, namespace'
      FieldExtractionRuleParseEnabled: true
      SumoAccessID: !Ref Section1bSumoAccessID
      SumoAccessKey: !Ref Section1cSumoAccessKey
      SumoDeployment: !Ref Section1aSumoDeployment
  
  GenericCloudWatchLogsFieldExtractionRule:
    Type: Custom::SumoLogicFieldExtractionRule
    Condition: create_cloudwatch_fer
    DependsOn: AddFunctionNameField
    Properties:
      ServiceToken: !Ref Section7aParentStackLambdaARN
      RemoveOnDeleteStack: false
      FieldExtractionRuleName: "AwsObservabilityGenericCloudWatchLogsFER"
      FieldExtractionRuleScope: "account=* region=* (_sourceHost=/aws/* or _sourceHost=API*Gateway*Execution*Logs*)"
      FieldExtractionRuleParseExpression: '| if (isEmpty(namespace),"unknown",namespace) as namespace
              | if (_sourceHost matches "/aws/lambda/*", "aws/lambda", namespace) as namespace
              | if (_sourceHost matches "/aws/rds/*", "aws/rds", namespace) as namespace
              | if (_sourceHost matches "/aws/ecs/containerinsights/*", "aws/ecs", namespace) as namespace
              | if (_sourceHost matches "/aws/kinesisfirehose/*", "aws/firehose", namespace) as namespace
              | if (_sourceHost matches "/aws/apigateway/*", "aws/apigateway", namespace) as namespace 
              | if (_sourceHost matches "API-Gateway-Execution-Logs*", "aws/apigateway", namespace) as namespace 
              | parse field=_sourceHost "/aws/lambda/*" as functionname nodrop
              | tolowercase(functionname) as functionname
              | parse field=_sourceHost "/aws/rds/*/*/" as f1, dbidentifier nodrop
              | parse field=_sourceHost "/aws/apigateway/*/*" as apiid, stage nodrop
              | parse field=_sourceHost "API-Gateway-Execution-Logs_*/*" as apiid, stage nodrop
              | apiid as apiName
              | tolowercase(dbidentifier) as dbidentifier
              | fields namespace, functionname, dbidentifier, apiid, apiName'
      FieldExtractionRuleParseEnabled: true
      SumoAccessID: !Ref Section1bSumoAccessID
      SumoAccessKey: !Ref Section1cSumoAccessKey
      SumoDeployment: !Ref Section1aSumoDeployment

  AddFunctionNameField:
    Type: Custom::SumoLogicFieldsSchema
    Properties:
      ServiceToken: !Ref Section7aParentStackLambdaARN
      FieldName: "functionname"
      RemoveOnDeleteStack: false
      SumoAccessID: !Ref Section1bSumoAccessID
      SumoAccessKey: !Ref Section1cSumoAccessKey
      SumoDeployment: !Ref Section1aSumoDeployment

Outputs:
  ExistingMetricSourceName:
    Description: "Existing CloudWatch Metrics Source Name"
    Condition: update_metrics_source
    Value: !GetAtt SumoMetricsUpdateSource.source_name
  ExistingCloudTrailLogSourceName:
    Description: "Existing CloudTrail Logs Source Name"
    Condition: update_cloudtrail_logs_source
    Value: !GetAtt SumoCloudTrailLogsUpdateSource.source_name
  ExistingCloudWatchLogSourceName:
    Description: "Existing CloudWatch Logs Source Name"
    Condition: update_cloudwatch_logs_source
    Value: !GetAtt SumoHTTPUpdateSource.source_name