AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: "Version - v2.12.0: Template to setup the ALB app with AWS and Sumo Logic resources for AWS Observability Solution."

Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: "Sumo Logic Access Configuration (Required)"
        Parameters:
          - Section1aSumoDeployment
          - Section1bSumoAccessID
          - Section1cSumoAccessKey
          - Section1dRemoveSumoResourcesOnDeleteStack
          - Section1eOrgId

      - Label:
          default: "Sumo Logic AWS Resources Tagging Configuration (Required)"
        Parameters:
          - Section2aAccountAlias
          - Section2bAccountAliasMappingS3URL

      - Label:
          default: "App Details - Sumo Logic App Configuration"
        Parameters:
          - Section3aInstallApp

      - Label:
          default: "App Details - CloudWatch Metrics Source Configuration"
        Parameters:
          - Section4aCloudWatchExistingSourceAPIUrl

      - Label:
          default: "App Details - ALB Source Log Source Configuration"
        Parameters:
          - Section5aALBLogsAPIUrl
          - Section5bALBLogsSourceName

      - Label:
          default: "Local Parameters. Do Not Edit the values."
        Parameters:
          - Section6aParentStackLambdaARN
          - Section6bTemplatesBucketName
          - Section6cNestedTemplateVersion

      - Label:
          default: "App Installation and sharing"
        Parameters:
          - Section7aAppInstallLocation
          - Section7bShare

    ParameterLabels:
      Section1aSumoDeployment:
        default: "Sumo Logic Deployment Name"
      Section1bSumoAccessID:
        default: "Sumo Logic Access ID"
      Section1cSumoAccessKey:
        default: "Sumo Logic Access Key"
      Section1dRemoveSumoResourcesOnDeleteStack:
        default: "Delete Sumo Logic Resources when stack is deleted"
      Section1eOrgId:
        default: "Sumo Logic Organization Id"

      Section2aAccountAlias:
        default: "Alias for AWS Account Identification. Please leave this blank if you are using CloudFormation StackSets to deploy the solution in multiple AWS accounts."

      Section2bAccountAliasMappingS3URL:
        default: "S3 URL of a CSV file that maps AWS Account IDs to an Account Alias"

      Section3aInstallApp:
        default: "Install Sumo Logic App"

      Section4aCloudWatchExistingSourceAPIUrl:
        default: "Existing Sumo Logic CloudWatch Metrics Source API URL"

      Section5aALBLogsAPIUrl:
        default: "Existing Sumo Logic ALB Logs Source API URL"
      Section5bALBLogsSourceName:
        default: "Provide the ALB Logs Source Name for Field Extraction Rule"

      Section6aParentStackLambdaARN:
        default: "If Any, Lambda ARN from parent Stack"
      Section6bTemplatesBucketName:
        default: "Nested Templates Bucket Name"
      Section6cNestedTemplateVersion:
        default: "Nested Templates Version"

      Section7aAppInstallLocation:
        default: "App Installation location"
      Section7bShare:
        default: "Share"

Parameters:
  Section1aSumoDeployment:
    Type: String
    Description: "Enter au, ca, de, eu, fed, in, jp, kr, us1 or us2"
    Default: ""
  Section1bSumoAccessID:
    Type: String
    Description: "Sumo Logic Access ID. Used for Sumo Logic API calls."
    AllowedPattern: ".+"
    ConstraintDescription: "Sumo Logic Access ID can not be empty."
  Section1cSumoAccessKey:
    Type: String
    Description: "Sumo Logic Access Key. Used for Sumo Logic API calls."
    AllowedPattern: ".+"
    ConstraintDescription: "Sumo Logic Access Key can not be empty."
    NoEcho: true
  Section1dRemoveSumoResourcesOnDeleteStack:
    AllowedValues:
      - true
      - false
    Default: true
    Description: "To delete collectors, sources and apps when the stack is deleted, set this parameter to True. Default is True.
                  Deletes the resources created by the stack. Deletion of updated resources will be skipped."
    Type: String
  Section1eOrgId:
    Description: "Appears on the Account Overview page that displays information about your Sumo Logic organization. Used for IAM Role in Sumo Logic AWS Sources. Visit https://help.sumologic.com/01Start-Here/05Customize-Your-Sumo-Logic-Experience/Preferences-Page"
    Type: String
    AllowedPattern: ".+"
    ConstraintDescription: "Sumo Logic Organization Id can not be empty."

  Section2aAccountAlias:
    Type: String
    Description: "Provide an Alias for AWS account for identification in Sumo Logic Explorer View, metrics and logs. Please do not include special characters."
    AllowedPattern: "[a-z0-9]*"
    ConstraintDescription: "Alias must only contain lowercase letters, number and length less than or equal to 30 characters."
    MaxLength: 30

  Section2bAccountAliasMappingS3URL:
    Type: String
    Description: "Required only if you are using CloudFormation StackSets to deploy the solution in multiple AWS accounts."
    Default: ""

  Section3aInstallApp:
    Type: String
    Description: "Yes - Installs the ALB App for the Sumo Logic AWS Observability Solution.
                  No - Skips the installation of this app."
    Default: 'Yes'
    AllowedValues:
      - 'Yes'
      - 'No'

  Section4aCloudWatchExistingSourceAPIUrl:
    Type: String
    Description: "Required when already collecting ALB Metrics. Provide the existing Sumo Logic ALB Metrics Source API URL. Account Field will be added to the Source. For Source API URL, visit https://help.sumologic.com/03Send-Data/Sources/03Use-JSON-to-Configure-Sources/Local-Configuration-File-Management/View-or-Download-Source-JSON-Configuration"
    Default: ""

  Section5aALBLogsAPIUrl:
    Type: String
    Description: "Required when already collecting ALB logs. Provide the existing Sumo Logic ALB Source API URL. Account, region and namespace Fields will be added to the Source. For Source API URL, visit https://help.sumologic.com/03Send-Data/Sources/03Use-JSON-to-Configure-Sources/Local-Configuration-File-Management/View-or-Download-Source-JSON-Configuration"
    Default: ""
  Section5bALBLogsSourceName:
    Type: String
    Description: "Provide a ALB Logs Source Name for Field Extraction Rule."
    Default: ""

  Section6aParentStackLambdaARN:
    Type: String
    Default: "ParentStackLambdaARN"
    Description: Parent Stack Lambda ARN. Do Not Edit the value.
  Section6bTemplatesBucketName:
    Type: String
    AllowedPattern: ".+"
    Description: Bucket Name for all the nested templates.
  Section6cNestedTemplateVersion:
    Type: String
    Description: "Provide the version for the nested templates. Default is the latest version."
    AllowedPattern: ".+"

  Section7aAppInstallLocation:
    Type: String
    Description: "Personal Folder - Installs App in user's Personal folder.
                  Admin Recommended Folder - Installs App in admin Recommended Folder"
    Default: 'Personal Folder'
    AllowedValues:
      - 'Personal Folder'
      - 'Admin Recommended Folder'
  Section7bShare:
    Type: String
    Description: "True - Installed App will be visible to all members of the organisation.
                  False - Installed App will be visible to you only."
    Default: 'True'
    AllowedValues:
      - 'True'
      - 'False'

Conditions:
  install_app: !Equals [!Ref Section3aInstallApp, 'Yes']

  update_alb_logs_source: !Not [!Equals [!Ref Section5aALBLogsAPIUrl, '']]

  update_alb_metrics_source: !Not [!Equals [!Ref Section4aCloudWatchExistingSourceAPIUrl, '']]

  create_fer: !Or
    - !Condition update_alb_logs_source
    - !Not [!Equals [!Ref Section5bALBLogsSourceName, '']]

Mappings:
  # Some buckets names have 's' or 'ss' in the region suffix. It is kept intentional as bucket names were not available.
  # Buckets names which are intentional -
  # 1. appdevzipfiles-eu-north-1s
  # 2. appdevzipfiles-ap-east-1s
  # 3. appdevzipfiles-af-south-1s
  # 4. appdevzipfiles-me-south-1s
  # 5. appdevzipfiles-me-central-1
  # 6. appdevzipfiles-eu-central-2ss
  # 7. appdevzipfiles-ap-northeast-3s
  # 8. appdevzipfiles-ap-southeast-3
  RegionMap:
    us-east-1:
      bucketname: appdevzipfiles-us-east-1
    us-east-2:
      bucketname: appdevzipfiles-us-east-2
    us-west-1:
      bucketname: appdevzipfiles-us-west-1
    us-west-2:
      bucketname: appdevzipfiles-us-west-2
    ap-south-1:
      bucketname: appdevzipfiles-ap-south-1
    ap-northeast-2:
      bucketname: appdevzipfiles-ap-northeast-2
    ap-southeast-1:
      bucketname: appdevzipfiles-ap-southeast-1
    ap-southeast-2:
      bucketname: appdevzipfiles-ap-southeast-2
    ap-northeast-1:
      bucketname: appdevzipfiles-ap-northeast-1
    ca-central-1:
      bucketname: appdevzipfiles-ca-central-1
    eu-central-1:
      bucketname: appdevzipfiles-eu-central-1
    eu-west-1:
      bucketname: appdevzipfiles-eu-west-1
    eu-west-2:
      bucketname: appdevzipfiles-eu-west-2
    eu-west-3:
      bucketname: appdevzipfiles-eu-west-3
    eu-north-1:
      bucketname: appdevzipfiles-eu-north-1s
    sa-east-1:
      bucketname: appdevzipfiles-sa-east-1
    ap-east-1:
      bucketname: appdevzipfiles-ap-east-1s
    af-south-1:
      bucketname: appdevzipfiles-af-south-1s
    eu-south-1:
      bucketname: appdevzipfiles-eu-south-1
    me-south-1:
      bucketname: appdevzipfiles-me-south-1s
    me-central-1:
      bucketname: appdevzipfiles-me-central-1
    eu-central-2:
        bucketname: appdevzipfiles-eu-central-2ss
    ap-northeast-3:
        bucketname: appdevzipfiles-ap-northeast-3s
    ap-southeast-3:
        bucketname: appdevzipfiles-ap-southeast-3

Resources:

  LambdaRole:
    Type: AWS::IAM::Role
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W11
            reason: "Operations are performed across resources."
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: LambdaExecutePolicies
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'

  LambdaHelper:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: main.handler
      Runtime: python3.13
      CodeUri:
        Bucket: !FindInMap [ RegionMap, !Ref 'AWS::Region', bucketname ]
        Key: "sumologic-aws-observability/apps/SumoLogicAWSObservabilityHelper/SumoLogicAWSObservabilityHelperv2.0.20.zip"
      MemorySize: 128
      Timeout: 900
      Role:
        Fn::GetAtt:
          - LambdaRole
          - Arn

  AccountAliasValue:
    Type: Custom::AccountAlias
    Properties:
      ServiceToken: !GetAtt LambdaHelper.Arn
      Region: !Ref "AWS::Region"
      AccountID: !Ref "AWS::AccountId"
      AccountAlias: !Ref Section2aAccountAlias
      AccountAliasMappingS3Url: !Ref Section2bAccountAliasMappingS3URL
      SumoAccessID: !Ref Section1bSumoAccessID
      SumoAccessKey: !Ref Section1cSumoAccessKey
      SumoDeployment: !Ref Section1aSumoDeployment

  sumoApp:
    Condition: install_app
    Type: Custom::App
    Properties:
      ServiceToken: !Ref Section6aParentStackLambdaARN
      Region: !Ref "AWS::Region"
      AppName: "AWS Observability Alb App"
      RemoveOnDeleteStack: !Ref Section1dRemoveSumoResourcesOnDeleteStack
      FolderName: !Sub "AWS Observability ${Section6cNestedTemplateVersion} "
      RetainOldAppOnUpdate: true
      SumoAccessID: !Ref Section1bSumoAccessID
      SumoAccessKey: !Ref Section1cSumoAccessKey
      SumoDeployment: !Ref Section1aSumoDeployment
      AppJsonS3Url: !Sub "https://${Section6bTemplatesBucketName}.s3.amazonaws.com/aws-observability-versions/${Section6cNestedTemplateVersion}/appjson/Alb-App.json"
      location: !Ref Section7aAppInstallLocation
      share: !Ref Section7bShare
      orgid: !Ref Section1eOrgId

  SumoALBLogsUpdateSource:
    Type: Custom::SumoLogicUpdateFields
    Condition: update_alb_logs_source
    Properties:
      ServiceToken: !Ref Section6aParentStackLambdaARN
      Region: !Ref "AWS::Region"
      RemoveOnDeleteStack: !Ref Section1dRemoveSumoResourcesOnDeleteStack
      SourceApiUrl: !Ref Section5aALBLogsAPIUrl
      SumoAccessID: !Ref Section1bSumoAccessID
      SumoAccessKey: !Ref Section1cSumoAccessKey
      SumoDeployment: !Ref Section1aSumoDeployment
      Fields:
        account: !GetAtt AccountAliasValue.ACCOUNT_ALIAS
        region: !Ref "AWS::Region"
        accountid: !Ref "AWS::AccountId"

  SumoALBMetricsUpdateSource:
    Type: Custom::SumoLogicUpdateFields
    Condition: update_alb_metrics_source
    Properties:
      ServiceToken: !Ref Section6aParentStackLambdaARN
      Region: !Ref "AWS::Region"
      RemoveOnDeleteStack: !Ref Section1dRemoveSumoResourcesOnDeleteStack
      SourceApiUrl: !Ref Section4aCloudWatchExistingSourceAPIUrl
      SumoAccessID: !Ref Section1bSumoAccessID
      SumoAccessKey: !Ref Section1cSumoAccessKey
      SumoDeployment: !Ref Section1aSumoDeployment
      Fields:
        account: !GetAtt AccountAliasValue.ACCOUNT_ALIAS

  AlbLogsFieldExtractionRule:
    Type: Custom::SumoLogicFieldExtractionRule
    Condition: create_fer
    Properties:
      ServiceToken: !Ref Section6aParentStackLambdaARN
      RemoveOnDeleteStack: false
      FieldExtractionRuleName: "AwsObservabilityAlbAccessLogsFER"
      FieldExtractionRuleScope: !Join
        - ""
        - - "(_source="
          - !If [update_alb_logs_source, !Sub "\"${SumoALBLogsUpdateSource.source_name}\"", !Ref Section5bALBLogsSourceName]
          - " (http or https or h2 or grpcs or ws or wss))"
      FieldExtractionRuleParseExpression: '| parse "* * * * * * * * * * * * \"*\" \"*\" * * * \"*\"" as Type, DateTime, loadbalancer, Client, Target, RequestProcessingTime, TargetProcessingTime, ResponseProcessingTime, ElbStatusCode, TargetStatusCode, ReceivedBytes, SentBytes, Request, UserAgent, SslCipher, SslProtocol, TargetGroupArn, TraceId
                                            | where Type in ("http", "https", "h2", "grpcs", "ws", "wss")
                                            | where !isBlank(loadbalancer)
                                            | "aws/applicationelb" as namespace
                                            | tolowercase(loadbalancer) as loadbalancer | fields loadbalancer, namespace'
      FieldExtractionRuleParseEnabled: true
      SumoAccessID: !Ref Section1bSumoAccessID
      SumoAccessKey: !Ref Section1cSumoAccessKey
      SumoDeployment: !Ref Section1aSumoDeployment

  AlbCloudTrailLogsFieldExtractionRule:
    Type: Custom::SumoLogicFieldExtractionRule
    Condition: create_fer
    Properties:
      ServiceToken: !Ref Section6aParentStackLambdaARN
      RemoveOnDeleteStack: false
      FieldExtractionRuleName: "AwsObservabilityALBCloudTrailLogsFER"
      FieldExtractionRuleScope: "account=* eventSource eventName \"elasticloadbalancing.amazonaws.com\" \"2015-12-01\""
      FieldExtractionRuleParseExpression: '| json "eventSource", "awsRegion", "recipientAccountId", "requestParameters.name", "requestParameters.type", "requestParameters.loadBalancerArn", "apiVersion" as event_source, region, accountid, loadbalancer, loadbalancertype, loadbalancerarn, api_version nodrop 
                                            | "" as namespace
                                            | where event_source = "elasticloadbalancing.amazonaws.com" and api_version matches "2015-12-01" 
                                            | parse field=loadbalancerarn ":loadbalancer/*/*/*" as balancertype, loadbalancer, f1 nodrop
                                            | if(loadbalancertype matches "network", "aws/nlb", if(balancertype matches "net", "aws/nlb", namespace)) as namespace
                                            | if(loadbalancertype matches "application", "aws/applicationelb", if(balancertype matches "app", "aws/applicationelb", namespace)) as namespace
                                            | where namespace="aws/applicationelb" or isEmpty(namespace)
                                            | toLowerCase(loadbalancer) as loadbalancer  
                                            | fields region, namespace, loadbalancer, accountid'
      FieldExtractionRuleParseEnabled: true
      SumoAccessID: !Ref Section1bSumoAccessID
      SumoAccessKey: !Ref Section1cSumoAccessKey
      SumoDeployment: !Ref Section1aSumoDeployment
Outputs:
  ExistingMetricSourceName:
    Description: "Existing CloudWatch Metrics Source Name"
    Condition: update_alb_metrics_source
    Value: !GetAtt SumoALBMetricsUpdateSource.source_name
  ExistingLogSourceName:
    Description: "Existing ALB Logs Source Name"
    Condition: update_alb_logs_source
    Value: !GetAtt SumoALBLogsUpdateSource.source_name