AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: "Template to setup the ALB app with AWS and Sumo Logic resources for AWS Observability Solution."

Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: "Sumo Logic Access Configuration (Required)"
        Parameters:
          - Section1aSumoDeployment
          - Section1bSumoAccessID
          - Section1cSumoAccessKey
          - Section1dSumoOrganizationId
          - Section1eRemoveSumoResourcesOnDeleteStack

      - Label:
          default: "Sumo Logic AWS Resources Tagging Configuration (Required)"
        Parameters:
          - Section2aTagExistingAWSResources
          - Section2bAccountAlias
          - Section2cFilterExpression

      - Label:
          default: "App Details - Sumo Logic App Configuration"
        Parameters:
          - Section3aInstallApp
          - Section3bCollectorName

      - Label:
          default: "App Details - CloudWatch Metrics Source Configuration"
        Parameters:
          - Section4aCreateCloudWatchMetricsSource
          - Section4bCloudWatchMetricsSourceName
          - Section4cCloudWatchExistingSourceAPIUrl

      - Label:
          default: "App Details - ALB Source Log Source Configuration"
        Parameters:
          - Section5aCreateS3Bucket
          - Section5bS3LogsBucketName
          - Section5cCreateALBLogSource
          - Section5dS3BucketPathExpression
          - Section5eALBLogsSourceName
          - Section5fALBLogsAPIUrl

      - Label:
          default: "Local Parameters. Do Not Edit the values."
        Parameters:
          - Section6aParentStackLambdaARN

    ParameterLabels:
      Section1aSumoDeployment:
        default: "Sumo Logic Deployment Name"
      Section1bSumoAccessID:
        default: "Sumo Logic Access ID"
      Section1cSumoAccessKey:
        default: "Sumo Logic Access Key"
      Section1dSumoOrganizationId:
        default: "Sumo Logic Organization Id"
      Section1eRemoveSumoResourcesOnDeleteStack:
        default: "Delete Sumo Logic Resources when stack is deleted"

      Section2aTagExistingAWSResources:
        default: "Tag Existing AWS ALB Resources."
      Section2bAccountAlias:
        default: "Alias for AWS Account Identification"
      Section2cFilterExpression:
        default: "Filter Regular expression"

      Section3aInstallApp:
        default: "Install Sumo Logic App"
      Section3bCollectorName:
        default: "Sumo Logic Collector Name"

      Section4aCreateCloudWatchMetricsSource:
        default: "Create Sumo Logic CloudWatch Metrics Source"
      Section4bCloudWatchMetricsSourceName:
        default: "Sumo Logic CloudWatch Metrics Source Name"
      Section4cCloudWatchExistingSourceAPIUrl:
        default: "Existing Sumo Logic CloudWatch Metrics Source API URL"

      Section5aCreateS3Bucket:
        default: "Create AWS S3 Bucket"
      Section5bS3LogsBucketName:
        default: "AWS S3 Bucket Name"
      Section5cCreateALBLogSource:
        default: "Create Sumo Logic ALB Logs Source"
      Section5dS3BucketPathExpression:
        default: "Path Expression for the logs"
      Section5eALBLogsSourceName:
        default: "Sumo Logic ALB Logs Source Name"
      Section5fALBLogsAPIUrl:
        default: "Existing Sumo Logic ALB Logs Source API URL"

      Section6aParentStackLambdaARN:
        default: "If Any, Lambda ARN from parent Stack"

Parameters:
  Section1aSumoDeployment:
    Type: String
    AllowedValues:
      - au
      - ca
      - de
      - eu
      - jp
      - us2
      - us1
      - in
      - fed
    Description: "Enter au, ca, de, eu, jp, us2, in, fed or us1."
  Section1bSumoAccessID:
    Type: String
    Description: "Sumo Logic Access ID. Used for Sumo Logic API calls."
    AllowedPattern: ".+"
    ConstraintDescription: "Sumo Logic Access ID can not be empty."
  Section1cSumoAccessKey:
    Type: String
    Description: "Sumo Logic Access Key. Used for Sumo Logic API calls."
    AllowedPattern: ".+"
    ConstraintDescription: "Sumo Logic Access Key can not be empty."
    NoEcho: true
  Section1dSumoOrganizationId:
    Description: "Appears on the Account Overview page that displays information about your Sumo Logic organization. Used for IAM Role in Sumo Logic AWS Sources."
    Type: String
    AllowedPattern: ".+"
    ConstraintDescription: "Sumo Logic Organization Id can not be empty."
  Section1eRemoveSumoResourcesOnDeleteStack:
    AllowedValues:
      - true
      - false
    Default: true
    Description: "To delete collectors, sources and apps when the stack is deleted, set this parameter to True. Default is True.
                  Deletes the resources created by the stack. Deletion of updated resources will be skipped."
    Type: String

  Section2aTagExistingAWSResources:
    Type: String
    Description: "Yes - Tags the existing AWS ALB resources with key - Value as account - account alias.
                  No - Skip AWS Resources tagging."
    Default: 'Yes'
    AllowedValues:
      - 'Yes'
      - 'No'
  Section2bAccountAlias:
    Type: String
    Description: "Provide an Alias for AWS account for identification in Sumo Logic Explorer View, metrics and logs. Please do not include special characters."
    AllowedPattern: "[a-zA-Z0-9]+"
    ConstraintDescription: "Alias must only contain uppercase, lowercase letters, number and length less than or equal to 30 characters."
    MaxLength: 30
  Section2cFilterExpression:
    Type: String
    Default: ""
    Description: "Provide regular expression for matching aws resources. For eg;- 'InstanceType': 't1.micro.*?'|'name': 'Test.*?']|'stageName': 'prod.*?'|'FunctionName': 'Test.*?'|TableName.*?|'LoadBalancerName': 'Test.*?'|'DBClusterIdentifier': 'Test.*?'|'DBInstanceIdentifier': 'Test.*?'"

  Section3aInstallApp:
    Type: String
    Description: "Yes - Installs the ALB App for the Sumo Logic AWS Observability Solution.
                  No - Skips the installation of this app."
    Default: 'Yes'
    AllowedValues:
      - 'Yes'
      - 'No'
  Section3bCollectorName:
    Type: String
    Description: "Provide a Sumo Logic Collector Name"
    Default: ""

  Section4aCreateCloudWatchMetricsSource:
    Type: String
    Description: "Yes - Creates a Sumo Logic CloudWatch Metrics Source which collects Metrics for multiple Namespaces from the region selected.
                  No - If you already have a CloudWatch Metrics Source collecting ALB metrics."
    Default: 'Yes'
    AllowedValues:
      - 'Yes'
      - 'No'
  Section4bCloudWatchMetricsSourceName:
    Type: String
    Description: "Provide a Cloud Watch Metrics Source Name"
    Default: ""
  Section4cCloudWatchExistingSourceAPIUrl:
    Type: String
    Description: "Required when already collecting ALB Metrics. Provide the existing Sumo Logic ALB Metrics Source API URL. Account Field will be added to the Source. For Source API URL, visit https://help.sumologic.com/03Send-Data/Sources/03Use-JSON-to-Configure-Sources/Local-Configuration-File-Management/View-or-Download-Source-JSON-Configuration"
    Default: ""

  Section5aCreateS3Bucket:
    Type: String
    Description: "Yes - Create a new S3 bucket in AWS S3.
                  No - Use an existing S3 bucket from AWS S3 which has ALB Logs."
    Default: 'Yes'
    AllowedValues:
      - 'Yes'
      - 'No'
  Section5bS3LogsBucketName:
    Type: String
    Description: "Existing Bucket Name - Provide value if the Flag is set to No.
                  New Bucket Name - Provide a unique Bucket Name if the flag is set to Yes."
    Default: ""
  Section5cCreateALBLogSource:
    Type: String
    Description: "Choose Yes to create Sumo Logic ALB Log Source with provided bucket Name."
    Default: 'Yes'
    AllowedValues:
      - 'Yes'
      - 'No'
  Section5dS3BucketPathExpression:
    Type: String
    Description: Path expression to match one or more S3 objects. For example, ABC*.log or ABC.log
    Default: "*"
  Section5eALBLogsSourceName:
    Type: String
    Description: "Provide a ALB Logs Source Name"
    Default: ""
  Section5fALBLogsAPIUrl:
    Type: String
    Description: "Required when already collecting ALB logs. Provide the existing Sumo Logic ALB Source API URL. Account, region and namespace Fields will be added to the Source. For Source API URL, visit https://help.sumologic.com/03Send-Data/Sources/03Use-JSON-to-Configure-Sources/Local-Configuration-File-Management/View-or-Download-Source-JSON-Configuration"
    Default: ""

  Section6aParentStackLambdaARN:
    Type: String
    Default: "ParentStackLambdaARN"
    Description: Parent Stack Lambda ARN. Do Not Edit the value.

Mappings:
  RegionMap:
    us-east-1:
      bucketname: appdevzipfiles-us-east-1
    us-east-2:
      bucketname: appdevzipfiles-us-east-2
    us-west-1:
      bucketname: appdevzipfiles-us-west-1
    us-west-2:
      bucketname: appdevzipfiles-us-west-2
    ap-south-1:
      bucketname: appdevzipfiles-ap-south-1
    ap-northeast-2:
      bucketname: appdevzipfiles-ap-northeast-2
    ap-southeast-1:
      bucketname: appdevzipfiles-ap-southeast-1
    ap-southeast-2:
      bucketname: appdevzipfiles-ap-southeast-2
    ap-northeast-1:
      bucketname: appdevzipfiles-ap-northeast-1
    ca-central-1:
      bucketname: appdevzipfiles-ca-central-1
    eu-central-1:
      bucketname: appdevzipfiles-eu-central-1
    eu-west-1:
      bucketname: appdevzipfiles-eu-west-1
    eu-west-2:
      bucketname: appdevzipfiles-eu-west-2
    eu-west-3:
      bucketname: appdevzipfiles-eu-west-3
    eu-north-1:
      bucketname: appdevzipfiles-eu-north-1s
    sa-east-1:
      bucketname: appdevzipfiles-sa-east-1
    ap-east-1:
      bucketname: appdevzipfiles-ap-east-1s
    af-south-1:
      bucketname: appdevzipfiles-af-south-1s
    eu-south-1:
      bucketname: appdevzipfiles-eu-south-1
    me-south-1:
      bucketname: appdevzipfiles-me-south-1s

Conditions:
  do_not_use_parent_stack: !Equals [ !Ref Section6aParentStackLambdaARN, "ParentStackLambdaARN"]

  tag_existing_aws_resources: !Equals [!Ref Section2aTagExistingAWSResources, 'Yes']
  install_app: !Equals [!Ref Section3aInstallApp, 'Yes']

  update_alb_logs_source: !And
    - !Not [!Equals [!Ref Section5fALBLogsAPIUrl, '']]
    - !Not [!Equals [!Ref Section5cCreateALBLogSource, 'Yes']]

  update_alb_metrics_source: !And
    - !Not [!Equals [!Ref Section4cCloudWatchExistingSourceAPIUrl, '']]
    - !Not [!Equals [!Ref Section4aCreateCloudWatchMetricsSource, 'Yes']]

Resources:

  WaitHandle:
    Type: "AWS::CloudFormation::WaitConditionHandle"

  CreateCommonResources:
    Type: AWS::CloudFormation::Stack
    Condition: do_not_use_parent_stack
    Properties:
      TemplateURL: !Join
        - ""
        - - "https://"
          - !FindInMap [RegionMap, !Ref 'AWS::Region', bucketname]
          - ".s3.amazonaws.com/sumologic-aws-observability/apps/common/resources.template.yaml"
      Parameters:
        SumoLogicDeployment: !Ref Section1aSumoDeployment
        SumoLogicAccessID: !Ref Section1bSumoAccessID
        SumoLogicAccessKey: !Ref Section1cSumoAccessKey
        SumoLogicOrganizationId: !Ref Section1dSumoOrganizationId
        RemoveSumoLogicResourcesOnDeleteStack: !Ref Section1eRemoveSumoResourcesOnDeleteStack
        AccountAlias: !Ref Section2bAccountAlias
        CollectorName: !Ref Section3bCollectorName
        CreateCloudWatchMetricsSource: !Ref Section4aCreateCloudWatchMetricsSource
        CloudWatchMetricsSourceName: !Ref Section4bCloudWatchMetricsSourceName
        CloudWatchMetricsNameSpaces: "AWS/ApplicationELB"
        CreateALBLogSource: !Ref Section5cCreateALBLogSource
        CreateALBS3Bucket: !Ref Section5aCreateS3Bucket
        ALBS3LogsBucketName: !Ref Section5bS3LogsBucketName
        ALBS3BucketPathExpression: !Ref Section5dS3BucketPathExpression
        ALBLogsSourceName: !Ref Section5eALBLogsSourceName

  TagAWSResources:
    Type: Custom::TagAWSResources
    Condition: tag_existing_aws_resources
    Properties:
      ServiceToken: !If [do_not_use_parent_stack, !GetAtt CreateCommonResources.Outputs.LambdaHelperARN, !Ref Section6aParentStackLambdaARN]
      RemoveOnDeleteStack: !Ref Section1eRemoveSumoResourcesOnDeleteStack
      Region: !Ref "AWS::Region"
      AWSResource: elbv2
      Tags:
        account: !Ref Section2bAccountAlias
      AccountID: !Ref "AWS::AccountId"
      Filter: !Ref Section2cFilterExpression

  ALBMetricRule:
    Type: Custom::SumoLogicMetricRules
    Properties:
      ServiceToken: !If [do_not_use_parent_stack, !GetAtt CreateCommonResources.Outputs.LambdaHelperARN, !Ref Section6aParentStackLambdaARN]
      RemoveOnDeleteStack: false
      MetricRuleName: "AwsObservabilityALBMetricsEntityRule"
      MatchExpression: "Namespace=AWS/ApplicationELB LoadBalancer=*"
      ExtractVariables:
        entity: "$LoadBalancer._1"
      SumoAccessID: !Ref Section1bSumoAccessID
      SumoAccessKey: !Ref Section1cSumoAccessKey
      SumoDeployment: !Ref Section1aSumoDeployment

  sumoApp:
    Condition: install_app
    Type: Custom::App
    Properties:
      ServiceToken: !If [do_not_use_parent_stack, !GetAtt CreateCommonResources.Outputs.LambdaHelperARN, !Ref Section6aParentStackLambdaARN]
      Region: !Ref "AWS::Region"
      AppName: "AWS Observability Alb App"
      Version: "1"
      RemoveOnDeleteStack: !Ref Section1eRemoveSumoResourcesOnDeleteStack
      FolderName: "Sumo Logic AWS Observability Apps "
      SumoAccessID: !Ref Section1bSumoAccessID
      SumoAccessKey: !Ref Section1cSumoAccessKey
      SumoDeployment: !Ref Section1aSumoDeployment

  ALBUpdateSourceWaitCondition:
    Type: "AWS::CloudFormation::WaitCondition"
    DependsOn: ALBMetricRule
    Properties:
      Handle: !Ref WaitHandle
      Timeout: "20"
      Count: 0

  SumoALBLogsUpdateSource:
    Type: Custom::SumoLogicUpdateFields
    Condition: update_alb_logs_source
    DependsOn: ALBUpdateSourceWaitCondition
    Properties:
      ServiceToken: !If [do_not_use_parent_stack, !GetAtt CreateCommonResources.Outputs.LambdaHelperARN, !Ref Section6aParentStackLambdaARN]
      Region: !Ref "AWS::Region"
      RemoveOnDeleteStack: !Ref Section1eRemoveSumoResourcesOnDeleteStack
      SourceApiUrl: !Ref Section5fALBLogsAPIUrl
      SumoAccessID: !Ref Section1bSumoAccessID
      SumoAccessKey: !Ref Section1cSumoAccessKey
      SumoDeployment: !Ref Section1aSumoDeployment
      Fields:
        account: !Ref Section2bAccountAlias
        namespace: "AWS/ApplicationELB"
        region: !Ref "AWS::Region"

  SumoALBMetricsUpdateSource:
    Type: Custom::SumoLogicUpdateFields
    Condition: update_alb_metrics_source
    DependsOn: ALBUpdateSourceWaitCondition
    Properties:
      ServiceToken: !If [do_not_use_parent_stack, !GetAtt CreateCommonResources.Outputs.LambdaHelperARN, !Ref Section6aParentStackLambdaARN]
      Region: !Ref "AWS::Region"
      RemoveOnDeleteStack: !Ref Section1eRemoveSumoResourcesOnDeleteStack
      SourceApiUrl: !Ref Section4cCloudWatchExistingSourceAPIUrl
      SumoAccessID: !Ref Section1bSumoAccessID
      SumoAccessKey: !Ref Section1cSumoAccessKey
      SumoDeployment: !Ref Section1aSumoDeployment
      Fields:
        account: !Ref Section2bAccountAlias

Outputs:
  ExistingMetricSourceName:
    Description: "Existing CloudWatch Metrics Source Name"
    Condition: update_alb_metrics_source
    Value: !GetAtt SumoALBMetricsUpdateSource.source_name
  ExistingLogSourceName:
    Description: "Existing ALB Logs Source Name"
    Condition: update_alb_logs_source
    Value: !GetAtt SumoALBLogsUpdateSource.source_name