AWSTemplateFormatVersion: '2010-09-09'
Description: Grandchild template that creates a resource.

Resources:
  GrandchildBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::Region}-23242123"

Outputs:
  GrandchildBucketName:
    Description: "Bucket created by the Grandchild stack"
    Value: !Ref GrandchildBucket
