name: "Azure TF template tests"
on:
  pull_request:
    paths:
      - 'azure-observability-terraform/**'

jobs:

  ValidateTF:
    runs-on: ubuntu-latest
    name: "Validatation (format & syntax)"
    defaults:
      run:
        working-directory: ./azure-observability-terraform
    steps:
    - uses: actions/checkout@v4
      name: Checkout source code

    - uses: hashicorp/setup-terraform@v3
      name: Setup Terraform
      # The default configuration installs the latest version of Terraform CLI
      # with:
      #   terraform_version: "1.1.7"

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check -recursive -diff
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate

  TFSecurityChecksUsingCheckov:
    name: "Security Checks (checkov)"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: bridgecrewio/checkov-action@master
        with:
          directory: 'azure-observability-terraform/'
          quiet: true
          framework: terraform
          output_format: cli
          output_bc_ids: false
          download_external_modules: true
          # skip_check:

  TFSecurityChecksUsingTfsec:
    name: "Security Checks (tfsec)"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working_directory: 'azure-observability-terraform/'
